site_name:  We4city API Docs
site_url: https://we4city-api-docs.readthedocs.io/
repo_url: https://github.com/we4city/api-doc.git
site_description: We4city API Documentation
docs_dir: docs
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://we4city.com/assets/css/readthedocs/main.css", "https://we4city.com/assets/css/readthedocs/core.css"]
extra_javascript: ["custom.js"]
google_analytics: ['UA-130184819-1', 'we4city.readthedocs.io']
pages:
  - 'Home': index.md
  - 'API Overview': 'api/overview.md'
  - 'Access':
    - 'Get Access Token': 'api/access/token.md'
  - 'Live Cameras': 'api/Cameras/index.md'
  - 'Webgis':
    - 'Overview': 'api/Webgis/index.md'
    - 'Geo Layers': 'api/Webgis/Layers.md'
    - 'Topics': 'api/Webgis/Topics.md'
    - 'Subtopics': 'api/Webgis/Subtopics.md'
  - 'IOT':
    - 'Overview': 'api/IOT/index.md'
    - 'DataModel': 'api/IOT/datamodel.md'
    - 'Entities': 'api/IOT/entities.md'
    - 'Networks': 'api/IOT/networks.md'
    - 'Network Branches': 'api/IOT/networkbranches.md'
    - 'Historical Data': 'api/IOT/history.md'
  - 'Advanced Filtering': 'advanced-filtering.md'
